version: '3.8'

services:
  db:
    image: postgres:15
    container_name: acme_hse_db
    restart: always
    environment:
      POSTGRES_USER: hse_user
      POSTGRES_PASSWORD: hse_password
      POSTGRES_DB: acme_hse
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/database/postgres_schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
