/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;
const swSelf = self as unknown as ServiceWorkerGlobalScope & typeof globalThis;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
precacheAndRoute(swSelf.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell.
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }: { request: Request; url: URL }) => {
    if (request.mode !== 'navigate') {
      return false;
    }
    if (url.pathname.startsWith('/_')) {
      return false;
    }
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }
    return true;
  },
  createHandlerBoundToURL('/index.html')
);

// Cache images with a Cache First strategy
registerRoute(
  ({ url }) => url.origin === swSelf.location.origin && url.pathname.endsWith('.png'),
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
swSelf.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    swSelf.skipWaiting();
  }
});

// Senior Level Offline Sync logic
swSelf.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-hse-reports') {
    event.waitUntil(processOfflineReports());
  }
});

async function processOfflineReports() {
    console.log("Background Sync: Processing offline HSE reports...");
    // In a real implementation, we would pull from IndexedDB and call the /sync API
}
